// Base musicale des ambiances du blind test.
//
// POURQUOI CE FICHIER EXISTE
//
// Jusqu'ici, une ambiance était une simple recherche de playlists sur Deezer :
// on prenait les trois playlists les plus suivies dont le titre ressemblait au
// thème, et on mélangeait leurs morceaux. Ces playlists sont faites par des
// inconnus, et la recherche de Deezer répond aussi sur la description et le
// contenu. Résultat constaté chez Chachou le 23/08 :
//
//   « Chanson française (Brel, Piaf…) » → Sam Smith, Lewis Capaldi,
//     OneRepublic, Bruno Mars EN BONNES RÉPONSES (une playlist de ballades
//     tristes avait été aspirée) ;
//   « Variété française » → Spice Girls, Britney Spears, Harry Styles,
//     Whitney Houston ;
//   « Années 2010 » → Billie Jean, Africa, Wake Me Up Before You Go-Go,
//     Sexual Healing… c'est-à-dire les années 80.
//
// La correction ne consiste pas à mieux filtrer une source non fiable, mais à
// changer de source : ici, chaque ambiance nomme ses artistes. Deezer ne sert
// plus qu'à retrouver les enregistrements et leurs extraits.
//
// FORMAT : 'Artiste' ou 'Artiste|Titre|Titre'.
//   - sans titre : on prend les morceaux les plus écoutés de l'artiste ;
//   - avec titres : on ne garde que ceux-là. C'est indispensable pour les
//     décennies — sans cela, « Années 90 » ramènerait le dernier album de
//     Mylène Farmer.

export const AMBIANCES = {
  // ---------------------------------------------------------------- décennies
  'annees 60 yeye': [
    'Johnny Hallyday|Que je t\'aime|Noir c\'est noir|Retiens la nuit',
    'Sylvie Vartan|La plus belle pour aller danser|Comme un garçon',
    'Françoise Hardy|Tous les garçons et les filles|Le temps de l\'amour|Comment te dire adieu',
    'France Gall|Poupée de cire, poupée de son|Laisse tomber les filles|Sacré Charlemagne',
    'Claude François|Belles, belles, belles|Comme d\'habitude|Cette année-là',
    'Sheila|L\'école est finie|Vous les copains',
    'Jacques Dutronc|Et moi, et moi, et moi|Il est cinq heures, Paris s\'éveille|Les cactus',
    'Michel Polnareff|La poupée qui fait non|Love Me, Please Love Me|Le bal des Laze',
    'Christophe|Aline|Les marionnettes',
    'Adamo|Tombe la neige|Vous permettez, Monsieur',
    'Richard Anthony|J\'entends siffler le train',
    'Nino Ferrer|Mirza|Le téléfon',
    'Antoine|Les Élucubrations d\'Antoine',
    'Serge Gainsbourg|Bonnie and Clyde|Je t\'aime... moi non plus',
    'The Beatles|Hey Jude|Yesterday|She Loves You|Twist and Shout',
    'The Rolling Stones|(I Can\'t Get No) Satisfaction|Paint It, Black',
    'The Beach Boys|Good Vibrations|Surfin\' U.S.A.',
    'Elvis Presley|Can\'t Help Falling in Love|Return to Sender',
    'The Animals|The House of the Rising Sun',
    'Petula Clark|Downtown',
  ],
  'annees 70': [
    'ABBA|Dancing Queen|Waterloo|Mamma Mia|S.O.S.',
    'Bee Gees|Stayin\' Alive|Night Fever|How Deep Is Your Love',
    'Queen|Bohemian Rhapsody|Somebody to Love|Killer Queen',
    'Pink Floyd|Another Brick in the Wall|Wish You Were Here|Money',
    'Led Zeppelin|Stairway to Heaven|Immigrant Song',
    'David Bowie|Heroes|Starman|Life on Mars?',
    'Elton John|Rocket Man|Your Song|Goodbye Yellow Brick Road',
    'Eagles|Hotel California',
    'Boney M.|Daddy Cool|Rasputin|Ma Baker',
    'Village People|Y.M.C.A.|In the Navy',
    'Gloria Gaynor|I Will Survive',
    'Donna Summer|Hot Stuff|I Feel Love',
    'Chic|Le Freak|Good Times',
    'Earth, Wind & Fire|September|Boogie Wonderland',
    'Joe Dassin|L\'été indien|Et si tu n\'existais pas|Les Champs-Élysées',
    'Claude François|Alexandrie Alexandra|Le lundi au soleil|Magnolias for ever',
    'Michel Sardou|La maladie d\'amour|Les vieux mariés',
    'Dalida|Gigi l\'amoroso|Laissez-moi danser|Il venait d\'avoir 18 ans',
    'Michel Fugain|Une belle histoire|Attention mesdames et messieurs',
    'Gérard Lenorman|La ballade des gens heureux',
    'Véronique Sanson|Amoureuse|Besoin de personne',
    'Christophe|Les mots bleus',
    'Nino Ferrer|Le Sud',
    'Michel Delpech|Le chasseur|Le Loir-et-Cher',
    'Julien Clerc|Ce n\'est rien|Ma préférence',
    'Alain Souchon|Allô maman bobo|J\'ai dix ans',
    'Sheila|Spacer',
    'Téléphone|Hygiaphone',
  ],
  'annees 80': [
    'Michael Jackson|Billie Jean|Beat It|Thriller|Smooth Criminal',
    'Madonna|Like a Virgin|Material Girl|La Isla Bonita|Papa Don\'t Preach',
    'Queen|I Want to Break Free|Radio Ga Ga|Under Pressure',
    'a-ha|Take On Me|The Sun Always Shines on T.V.',
    'Toto|Africa|Rosanna',
    'Wham!|Wake Me Up Before You Go-Go|Careless Whisper',
    'Cyndi Lauper|Girls Just Want to Have Fun|Time After Time',
    'Prince|Purple Rain|Kiss',
    'The Police|Every Breath You Take|Message in a Bottle',
    'Eurythmics|Sweet Dreams (Are Made of This)',
    'Tears for Fears|Shout|Everybody Wants to Rule the World',
    'Dead or Alive|You Spin Me Round (Like a Record)',
    'Bon Jovi|Livin\' on a Prayer|You Give Love a Bad Name',
    'Europe|The Final Countdown',
    'Survivor|Eye of the Tiger',
    'Whitney Houston|I Wanna Dance with Somebody',
    'Rick Astley|Never Gonna Give You Up',
    'Depeche Mode|Just Can\'t Get Enough|People Are People',
    'Jean-Jacques Goldman|Je te donne|Quand la musique est bonne|Envole-moi|Il changeait la vie',
    'Indochine|L\'aventurier|Trois nuits par semaine|Canary Bay',
    'Téléphone|Un autre monde|Cendrillon|New York avec toi',
    'Daniel Balavoine|L\'Aziza|Mon fils ma bataille|Vivre ou survivre',
    'France Gall|Ella, elle l\'a|Résiste|Babacar',
    'Michel Berger|La groupie du pianiste',
    'Étienne Daho|Week-end à Rome|Duel au soleil',
    'Niagara|J\'ai vu|Tchiki boum',
    'Jeanne Mas|En rouge et noir|Toute première fois',
    'Desireless|Voyage, voyage',
    'Images|Les démons de minuit',
    'Début de Soirée|Nuit de folie',
    'Partenaire Particulier|Partenaire particulier',
    'Elsa|T\'en va pas',
    'Vanessa Paradis|Joe le taxi',
    'Les Rita Mitsouko|Marcia Baila|C\'est comme ça',
    'Renaud|Mistral gagnant|Morgane de toi|Dès que le vent soufflera',
    'Julien Clerc|Femmes je vous aime',
    'Laurent Voulzy|Belle-Île-en-Mer, Marie-Galante',
    'Gold|Ville de lumière',
  ],
  'annees 90': [
    'Nirvana|Smells Like Teen Spirit|Come as You Are|Lithium',
    'Whitney Houston|I Will Always Love You',
    'Céline Dion|Pour que tu m\'aimes encore|My Heart Will Go On|Je sais pas',
    'Backstreet Boys|Everybody (Backstreet\'s Back)|I Want It That Way',
    'Spice Girls|Wannabe|Say You\'ll Be There|Spice Up Your Life',
    'Oasis|Wonderwall|Don\'t Look Back in Anger',
    'Blur|Song 2',
    'Radiohead|Creep',
    'Britney Spears|...Baby One More Time',
    'Ricky Martin|Livin\' la Vida Loca|María',
    'Lou Bega|Mambo No. 5',
    'Los del Río|Macarena',
    'Ace of Base|All That She Wants|The Sign',
    'Haddaway|What Is Love',
    'Snap!|Rhythm Is a Dancer',
    '2 Unlimited|No Limit',
    'Dr. Alban|It\'s My Life',
    'Corona|The Rhythm of the Night',
    'Mylène Farmer|Désenchantée|XXL|California',
    'Patrick Bruel|Qui a le droit',
    'MC Solaar|Caroline|Bouge de là|Nouveau Western',
    'IAM|Je danse le Mia|L\'Empire du côté obscur|Petit frère',
    'Alain Souchon|Foule sentimentale',
    'Francis Cabrel|Je t\'aimais, je t\'aime et je t\'aimerai|La corrida',
    'Manau|La tribu de Dana',
    'Era|Ameno',
    'Louise Attaque|J\'t\'emmène au vent|Léa',
    'Zebda|Tomber la chemise',
    'Michael Jackson|Black or White|Earth Song|They Don\'t Care About Us',
    'Coolio|Gangsta\'s Paradise',
    'The Cranberries|Zombie|Dreams',
    'No Doubt|Don\'t Speak',
    'R.E.M.|Losing My Religion|Everybody Hurts',
    'Red Hot Chili Peppers|Under the Bridge|Californication',
    'Aqua|Barbie Girl',
    'Eiffel 65|Blue (Da Ba Dee)',
    'Vengaboys|Boom, Boom, Boom, Boom!!',
    'Roch Voisine|Hélène',
    'Pascal Obispo|Lucie',
    'Doc Gynéco|Nirvana',
  ],
  'hits 2000': [
    'Britney Spears|Oops!... I Did It Again|Toxic',
    'Eminem|Lose Yourself|Without Me|The Real Slim Shady',
    'Usher|Yeah!|Burn',
    'Rihanna|Umbrella|Don\'t Stop the Music',
    'Beyoncé|Crazy in Love|Irreplaceable',
    'Shakira|Whenever, Wherever|Hips Don\'t Lie',
    'Coldplay|Clocks|Viva la Vida|The Scientist',
    'Amy Winehouse|Rehab|Back to Black|Valerie',
    'Gnarls Barkley|Crazy',
    'OutKast|Hey Ya!',
    'Black Eyed Peas|Where Is the Love?|Boom Boom Pow|I Gotta Feeling',
    'Kylie Minogue|Can\'t Get You Out of My Head',
    'Daft Punk|One More Time|Harder, Better, Faster, Stronger',
    'Kyo|Dernière danse|Le graal',
    'Calogero|Face à la mer|En apesanteur|Yalla',
    'Diam\'s|La Boulette|Jeune Demoiselle',
    'K-Maro|Femme Like U',
    'Tragédie|Hey Oh',
    'Corneille|Parce qu\'on vient de loin',
    'Superbus|Butterfly|Lola',
    'Christophe Maé|On s\'attache|Ça fait mal',
    'Sean Paul|Temperature|Get Busy',
    'Nelly Furtado|Say It Right|Maneater',
    'Gorillaz|Feel Good Inc.|Clint Eastwood',
    'Linkin Park|In the End|Numb',
    'Evanescence|Bring Me to Life',
    'Green Day|American Idiot|Boulevard of Broken Dreams',
    'Avril Lavigne|Complicated|Girlfriend',
    'Maroon 5|This Love',
    'The Killers|Mr. Brightside',
    'Lady Gaga|Poker Face|Just Dance',
    'Katy Perry|I Kissed a Girl|Hot n Cold',
    'Justin Timberlake|SexyBack|Cry Me a River',
    'Alizée|Moi... Lolita|J\'en ai marre !',
    'Jenifer|Au soleil',
    'Bénabar|Le dîner',
    'Raphaël|Caravane',
    'Grégoire|Toi + Moi',
    'Mika|Grace Kelly|Relax, Take It Easy',
    'Yannick Noah|Aux arbres citoyens',
  ],
  'annees 2010': [
    'Stromae|Alors on danse|Papaoutai|Formidable|Tous les mêmes',
    'Daft Punk|Get Lucky|Instant Crush',
    'Pharrell Williams|Happy',
    'Adele|Rolling in the Deep|Someone Like You|Hello',
    'Maître Gims|Bella|Sapés comme jamais|Est-ce que tu m\'aimes ?',
    'Christine and the Queens|Christine|Saint Claude',
    'Louane|Avenir|Jour 1',
    'Kendji Girac|Color Gitano|Andalouse',
    'Black M|Sur ma route',
    'Indila|Dernière danse|Tourner dans le vide',
    'Ed Sheeran|Shape of You|Thinking Out Loud|Perfect',
    'Bruno Mars|Just the Way You Are|Locked Out of Heaven|24K Magic',
    'Rihanna|We Found Love|Diamonds',
    'David Guetta|Titanium|She Wolf (Falling to Pieces)',
    'Avicii|Wake Me Up|Hey Brother',
    'Justin Bieber|Sorry|Love Yourself',
    'Sia|Chandelier|Cheap Thrills',
    'Orelsan|Basique|La pluie',
    'Vianney|Je m\'en vais|Pas là',
    'Julien Doré|Paris-Seychelles',
    'Angèle|Balance ton quoi|Tout oublier',
    'Aya Nakamura|Djadja|Pookie',
    'Soprano|Cosmo|Le diable ne s\'habille plus en Prada',
    'Amir|J\'ai cherché',
    'Clean Bandit|Rockabye|Rather Be',
    'Luis Fonsi|Despacito',
    'OMI|Cheerleader',
    'Mika|Elle me dit',
    'Zaz|Je veux',
    'Passenger|Let Her Go',
    'Lorde|Royals',
    'Coldplay|Paradise|A Sky Full of Stars',
    'Imagine Dragons|Radioactive|Believer',
    'The Weeknd|Blinding Lights|Can\'t Feel My Face',
    'Dua Lipa|New Rules|IDGAF',
    'Calvin Harris|One Kiss|This Is What You Came For',
    'Nekfeu|On verra',
    'Kungs|This Girl',
    'Petit Biscuit|Sunset Lover',
    'Shakira|Waka Waka (This Time for Africa)',
  ],

  // ------------------------------------------------------------- francophonie
  'variete francaise': [
    // Titres nommés là aussi : sans cela le catalogue remontait « Ma maison
    // c'est ta maison » de Garou ou les reprises en anglais de Patricia Kaas,
    // qui n'ont rien à faire dans un blind test de variété française.
    'Jean-Jacques Goldman|Je te donne|Quand la musique est bonne|Envole-moi|Il changeait la vie|Là-bas',
    'Francis Cabrel|Je l\'aime à mourir|Petite Marie|La corrida|Octobre|C\'est écrit',
    'Michel Sardou|Les lacs du Connemara|En chantant|Je vais t\'aimer|La maladie d\'amour',
    'Johnny Hallyday|Allumer le feu|Que je t\'aime|L\'envie|Quelque chose de Tennessee',
    'Céline Dion|Pour que tu m\'aimes encore|Je sais pas|S\'il suffisait d\'aimer|D\'amour ou d\'amitié',
    'Patrick Bruel|Casser la voix|Qui a le droit|Place des grands hommes|J\'te l\'dis quand même',
    'Florent Pagny|Savoir aimer|Ma liberté de penser|Chanter|Caruso',
    'Calogero|En apesanteur|Face à la mer|Si seulement je pouvais lui manquer|Le portrait',
    'Renaud|Mistral gagnant|Morgane de toi|Dès que le vent soufflera|Manhattan-Kaboul',
    'Indochine|L\'aventurier|Trois nuits par semaine|J\'ai demandé à la lune|Canary Bay',
    'Téléphone|Cendrillon|Un autre monde|New York avec toi|Ça (c\'est vraiment toi)',
    'Mylène Farmer|Désenchantée|Libertine|Sans contrefaçon|California',
    'Alain Souchon|Foule sentimentale|Allô maman bobo|J\'ai dix ans|Et si en plus y\'a personne',
    'France Gall|Ella, elle l\'a|Résiste|Il jouait du piano debout|Évidemment',
    'Daniel Balavoine|L\'Aziza|Mon fils ma bataille|Je ne suis pas un héros|Vivre ou survivre',
    'Julien Clerc|Femmes je vous aime|Ce n\'est rien|Ma préférence|Mélissa',
    'Michel Berger|La groupie du pianiste|Le paradis blanc|Quelques mots d\'amour',
    'Véronique Sanson|Amoureuse|Besoin de personne|Chanson sur ma drôle de vie',
    'Michel Delpech|Le chasseur|Pour un flirt|Le Loir-et-Cher|Que Marianne était jolie',
    'Étienne Daho|Week-end à Rome|Duel au soleil|Le grand sommeil',
    'Louise Attaque|J\'t\'emmène au vent|Léa|Ton invitation',
    'Vanessa Paradis|Joe le taxi|Divine idylle|Il y a',
    'Zazie|Je suis un homme|Un point c\'est toi|Zen|Rue de la paix',
    'Pascal Obispo|Lucie|Fan|Tombé pour elle',
    'Patricia Kaas|Mon mec à moi|Mademoiselle chante le blues|D\'Allemagne',
    'Lara Fabian|Je t\'aime|Tout|La différence',
    'Garou|Belle|Seul|Sous le vent',
    'Laurent Voulzy|Rockollection|Belle-Île-en-Mer, Marie-Galante|Le soleil donne',
    'Yannick Noah|Saga Africa|Aux arbres citoyens|Donne-moi une vie',
    'Christophe Maé|On s\'attache|Ça fait mal|Il est où le bonheur|Belle demoiselle',
    'Amel Bent|Ma philosophie|Le droit à l\'erreur',
    'Louane|Avenir|Jour 1|Si t\'étais là',
    'Vianney|Je m\'en vais|Pas là|Moi aimer toi',
    'Julien Doré|Paris-Seychelles|Le lac|Kiki',
    'Zaz|Je veux|On ira|Éblouie par la nuit',
    'Kendji Girac|Color Gitano|Andalouse|Conmigo',
    'Soprano|Cosmo|Clown|Mon précieux',
    'Christine and the Queens|Christine|Saint Claude|Tilted',
    'Angèle|Balance ton quoi|Tout oublier|Bruxelles je t\'aime',
    'Clara Luciani|La grenade|Respire encore|Ma sœur',
    'Bénabar|Le dîner|L\'effet papillon|Dis-lui oui',
    'Raphaël|Caravane|Ne partons pas fâchés',
    'Jenifer|Au soleil|Donne-moi le temps|Je danse',
    'Hélène Ségara|Il y a trop de gens qui t\'aiment|Vivo per lei|Elle, tu l\'aimes',
    'Grand Corps Malade|Roméo kiffe Juliette|Mesdames|Funambule',
    'Thomas Dutronc|J\'aime plus Paris|Comme un manouche sans guitare',
  ],
  'chanson francaise brel piaf': [
    // Les monuments sont nommés chanson par chanson : sur ce répertoire, le
    // catalogue met souvent en avant des enregistrements tardifs ou des faces B
    // que personne ne reconnaîtrait en quinze secondes.
    'Jacques Brel|Ne me quitte pas|Amsterdam|La valse à mille temps|Le plat pays|Quand on n\'a que l\'amour',
    'Édith Piaf|La vie en rose|Non, je ne regrette rien|Milord|L\'hymne à l\'amour|Padam Padam',
    'Georges Brassens|Les copains d\'abord|Chanson pour l\'Auvergnat|La mauvaise réputation|Le gorille|Les amoureux des bancs publics',
    'Charles Aznavour|La bohème|Emmenez-moi|For Me Formidable|Hier encore|Que c\'est triste Venise',
    'Léo Ferré|Avec le temps|C\'est extra|Jolie Môme|Paris canaille',
    'Barbara|L\'aigle noir|Ma plus belle histoire d\'amour|Nantes|Göttingen|Dis, quand reviendras-tu ?',
    'Charles Trenet|La mer|Douce France|Boum !|Y\'a d\'la joie',
    'Yves Montand|Les feuilles mortes|À bicyclette|C\'est si bon',
    'Serge Reggiani|Il suffirait de presque rien|Ma fille|Sarah|Le petit garçon',
    'Jean Ferrat|La montagne|Que serais-je sans toi|Nuit et brouillard|Ma France',
    'Serge Gainsbourg|La javanaise|Le poinçonneur des Lilas|Aux armes et cætera|La chanson de Prévert',
    'Juliette Gréco|Déshabillez-moi|Sous le ciel de Paris|La javanaise',
    'Gilbert Bécaud|Nathalie|Et maintenant|L\'important c\'est la rose',
    'Claude Nougaro|Toulouse|Cécile ma fille|Armstrong|Le jazz et la java',
    'Georges Moustaki|Le métèque|Ma liberté|Il y avait un jardin',
    'Maxime Le Forestier|San Francisco|Né quelque part|Mon frère',
    'Anne Sylvestre|Les gens qui doutent|Une sorcière comme les autres',
    'Guy Béart|L\'eau vive|Qu\'on est bien',
    'Félix Leclerc|Le p\'tit bonheur|Moi, mes souliers|L\'hymne au printemps',
    'Hugues Aufray|Santiano|Céline|Stewball',
    'Nana Mouskouri|Le temps des cerises|L\'enfant au tambour',
    'Pierre Perret|Les jolies colonies de vacances|Lily|Le tord-boyaux',
    'Bourvil|La tactique du gendarme|Salade de fruits|Les crayons',
    'Mouloudji|Comme un p\'tit coquelicot|Le déserteur',
    'Michel Legrand|Les moulins de mon cœur|Les parapluies de Cherbourg',
  ],
  'rap francais': [
    'IAM', 'NTM', 'MC Solaar', 'Oxmo Puccino', 'Diam\'s', 'Sexion d\'Assaut',
    'Orelsan', 'Nekfeu', 'Bigflo & Oli', 'Lomepal', 'Georgio', 'Dinos',
    'Hatik', 'Soolking', 'Kery James', 'Youssoupha', 'Médine', 'Disiz',
    'Fonky Family', 'Ärsenik', 'Assassin', 'Grand Corps Malade', 'Black M',
    'Maître Gims', 'Dadju', 'Soprano', 'Abd al Malik', 'Casseurs Flowters',
  ],
  'rap us': [
    '2Pac', 'The Notorious B.I.G.', 'Nas', 'JAY-Z', 'Eminem', 'Snoop Dogg',
    'Dr. Dre', 'Kanye West', 'Kendrick Lamar', 'Drake', 'J. Cole',
    'Travis Scott', 'Lil Wayne', '50 Cent', 'Ice Cube', 'Run-DMC',
    'Beastie Boys', 'A Tribe Called Quest', 'Wu-Tang Clan', 'Missy Elliott',
    'Nicki Minaj', 'Post Malone', 'Childish Gambino', 'Common', 'Ludacris',
    'Busta Rhymes', 'Nelly', 'Jay Rock',
  ],
  'r&b soul': [
    'Aretha Franklin', 'Marvin Gaye', 'Stevie Wonder', 'Otis Redding',
    'Ray Charles', 'Sam Cooke', 'James Brown', 'Al Green', 'Curtis Mayfield',
    'Bill Withers', 'Diana Ross', 'The Temptations', 'Whitney Houston',
    'Mariah Carey', 'Alicia Keys', 'Beyoncé', 'Usher', 'TLC',
    'Destiny\'s Child', 'Lauryn Hill', 'Erykah Badu', 'D\'Angelo',
    'John Legend', 'Amy Winehouse', 'Ne-Yo', 'Craig David', 'Mary J. Blige',
    'Boyz II Men', 'Luther Vandross', 'Etta James',
  ],
  'pop internationale': [
    'Michael Jackson', 'Madonna', 'Adele', 'Ed Sheeran', 'Taylor Swift',
    'Rihanna', 'Beyoncé', 'Bruno Mars', 'Coldplay', 'Maroon 5', 'Katy Perry',
    'Lady Gaga', 'Justin Timberlake', 'Dua Lipa', 'The Weeknd', 'Sia',
    'Shakira', 'Robbie Williams', 'George Michael', 'Elton John',
    'Whitney Houston', 'Britney Spears', 'Christina Aguilera', 'P!nk',
    'Harry Styles', 'Billie Eilish', 'Sam Smith', 'Lorde', 'Miley Cyrus',
    'Justin Bieber',
  ],

  // ---------------------------------------------------------------- genres
  rock: [
    'The Beatles', 'The Rolling Stones', 'Led Zeppelin', 'Pink Floyd', 'Queen',
    'AC/DC', 'Nirvana', 'Guns N\' Roses', 'U2', 'The Who', 'Deep Purple',
    'Aerosmith', 'Bon Jovi', 'The Doors', 'Jimi Hendrix', 'Bruce Springsteen',
    'Dire Straits', 'Fleetwood Mac', 'Radiohead', 'Oasis',
    'Red Hot Chili Peppers', 'Foo Fighters', 'Muse', 'The Police',
    'David Bowie', 'Eagles', 'Creedence Clearwater Revival', 'ZZ Top',
    'Scorpions', 'The Clash',
  ],
  'rock francais': [
    'Téléphone', 'Noir Désir', 'Indochine', 'Trust', 'Louise Attaque',
    'Les Rita Mitsouko', 'Mano Negra', 'Les Négresses Vertes', 'Dionysos',
    'BB Brunes', 'Superbus', 'Kyo', 'Saez', 'Luke', 'Deportivo',
    'Shaka Ponk', 'Skip The Use', 'Eiffel', 'No One Is Innocent',
    'Les Wampas', 'Bérurier Noir', 'Matmatah', 'Silmarils', 'Pleymo',
    'Marcel et son orchestre', 'La Souris Déglinguée',
  ],
  metal: [
    'Metallica', 'Iron Maiden', 'Black Sabbath', 'Judas Priest', 'Slayer',
    'Megadeth', 'Pantera', 'Slipknot', 'System of a Down', 'Rammstein',
    'Nightwish', 'Within Temptation', 'Sepultura', 'Motörhead', 'Anthrax',
    'Korn', 'Disturbed', 'Avenged Sevenfold', 'Gojira', 'Mass Hysteria',
    'In Flames', 'Children of Bodom', 'Opeth', 'Dream Theater',
    'Amon Amarth', 'Arch Enemy', 'Lamb of God', 'Bring Me The Horizon',
  ],
  'electro house': [
    'Daft Punk', 'David Guetta', 'Calvin Harris', 'Avicii',
    'Swedish House Mafia', 'Martin Garrix', 'Tiësto', 'Armin van Buuren',
    'deadmau5', 'Bob Sinclar', 'Justice', 'Cassius', 'Étienne de Crécy',
    'Modjo', 'Stardust', 'Alan Walker', 'Kygo', 'Robin Schulz', 'Kungs',
    'Petit Biscuit', 'The Chainsmokers', 'Disclosure', 'Duke Dumont',
    'Fatboy Slim', 'Basement Jaxx', 'Above & Beyond',
  ],
  techno: [
    'Jeff Mills', 'Carl Cox', 'Richie Hawtin', 'Laurent Garnier',
    'Charlotte de Witte', 'Amelie Lens', 'Nina Kraviz', 'Adam Beyer',
    'Underworld', 'The Chemical Brothers', 'Aphex Twin', 'Derrick May',
    'Juan Atkins', 'Kevin Saunderson', 'Sven Väth', 'Paul Kalkbrenner',
    'Boris Brejcha', 'Ben Klock', 'Marcel Dettmann', 'Rone', 'Vitalic',
    'Miss Kittin', 'Agoria', 'Gesaffelstein',
  ],
  'disco funk': [
    'CHIC', 'Earth, Wind & Fire', 'Kool & The Gang', 'Donna Summer',
    'Bee Gees', 'Gloria Gaynor', 'Sister Sledge', 'Village People',
    'KC & The Sunshine Band', 'The Trammps', 'Boney M.', 'Diana Ross',
    'Barry White', 'James Brown', 'Parliament', 'Funkadelic', 'Rick James',
    'Cameo', 'The Gap Band', 'Shalamar', 'Jamiroquai', 'Cerrone', 'Ottawan',
    'Patrick Hernandez', 'Amii Stewart', 'Anita Ward', 'Nile Rodgers',
  ],
  reggae: [
    'Bob Marley & The Wailers', 'Peter Tosh', 'Jimmy Cliff', 'Burning Spear',
    'Toots & The Maytals', 'Gregory Isaacs', 'Dennis Brown', 'Alpha Blondy',
    'Tiken Jah Fakoly', 'Israel Vibration', 'Steel Pulse', 'UB40',
    'Inner Circle', 'Damian Marley', 'Ziggy Marley', 'Groundation',
    'Danakil', 'Dub Inc', 'Sinsemilia', 'Pierpoljak', 'Tryo',
    'Yaniss Odua', 'Naâman', 'Biga Ranx',
  ],
  'latino reggaeton': [
    'Daddy Yankee', 'Don Omar', 'Wisin & Yandel', 'J Balvin', 'Maluma',
    'Bad Bunny', 'Ozuna', 'Nicky Jam', 'KAROL G', 'Shakira', 'Ricky Martin',
    'Enrique Iglesias', 'Luis Fonsi', 'Marc Anthony', 'Juanes',
    'Carlos Vives', 'Romeo Santos', 'Prince Royce', 'ROSALÍA', 'Sech',
    'Farruko', 'Rauw Alejandro', 'Manu Chao', 'Gipsy Kings',
  ],
  afrobeat: [
    'Fela Kuti', 'Tony Allen', 'Burna Boy', 'WizKid', 'Davido', 'Yemi Alade',
    'Angélique Kidjo', 'Salif Keita', 'Youssou N\'Dour', 'Amadou & Mariam',
    'Tiken Jah Fakoly', 'Alpha Blondy', 'Magic System', 'Koffi Olomidé',
    'Fally Ipupa', 'Papa Wemba', 'Awilo Longomba', 'Manu Dibango',
    'Rokia Traoré', 'Ali Farka Touré', 'Femi Kuti', 'Mr Eazi', 'Rema',
    'CKay', 'Dadju',
  ],
  'zouk & antilles': [
    'Kassav\'', 'Zouk Machine', 'Malavoi', 'Kali', 'Jacob Desvarieux',
    'Patrick Saint-Éloi', 'Édith Lefel', 'Tanya Saint-Val', 'Jocelyne Béroard',
    'Jean-Philippe Marthély', 'Fanny J', 'Warren', 'Lynnsha', 'Perle Lama',
    'Slaï', 'Medhy Custos', 'Admiral T', 'Kalash', 'Saïk', 'Krys',
    'Francky Vincent', 'Orlane', 'Misié Sadik', 'Jean-Michel Rotin',
  ],
  'k-pop': [
    'BTS', 'BLACKPINK', 'EXO', 'TWICE', 'Red Velvet', 'Girls\' Generation',
    'BIGBANG', '2NE1', 'SUPER JUNIOR', 'SHINee', 'NCT 127', 'Stray Kids',
    'ITZY', '(G)I-DLE', 'SEVENTEEN', 'MONSTA X', 'TOMORROW X TOGETHER',
    'ATEEZ', 'IVE', 'NewJeans', 'LE SSERAFIM', 'aespa', 'PSY', 'IU',
  ],
  jazz: [
    'Louis Armstrong', 'Duke Ellington', 'Miles Davis', 'John Coltrane',
    'Ella Fitzgerald', 'Billie Holiday', 'Nina Simone', 'Charlie Parker',
    'Thelonious Monk', 'Dizzy Gillespie', 'Chet Baker', 'Dave Brubeck',
    'Herbie Hancock', 'Sarah Vaughan', 'Stan Getz', 'Django Reinhardt',
    'Sidney Bechet', 'Oscar Peterson', 'Bill Evans', 'Sonny Rollins',
    'Wes Montgomery', 'Nat King Cole', 'Norah Jones', 'Diana Krall',
    'Michel Petrucciani', 'Claude Nougaro',
  ],
  'musique classique': [
    'Ludwig van Beethoven', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach',
    'Frédéric Chopin', 'Pyotr Ilyich Tchaikovsky', 'Antonio Vivaldi',
    'Claude Debussy', 'Erik Satie', 'Maurice Ravel', 'Giuseppe Verdi',
    'Richard Wagner', 'Franz Schubert', 'Johannes Brahms',
    'George Frideric Handel', 'Camille Saint-Saëns', 'Gabriel Fauré',
    'Edvard Grieg', 'Sergei Rachmaninoff', 'Igor Stravinsky', 'Georges Bizet',
    'Gioachino Rossini', 'Franz Liszt', 'Joseph Haydn', 'Gustav Mahler',
  ],
  country: [
    'Johnny Cash', 'Dolly Parton', 'Willie Nelson', 'Kenny Rogers',
    'Garth Brooks', 'Shania Twain', 'Alan Jackson', 'George Strait',
    'Tim McGraw', 'Faith Hill', 'Carrie Underwood', 'Blake Shelton',
    'Luke Bryan', 'Keith Urban', 'Brad Paisley', 'Zac Brown Band',
    'Rascal Flatts', 'Chris Stapleton', 'Kacey Musgraves', 'Miranda Lambert',
    'Hank Williams', 'Patsy Cline', 'Emmylou Harris', 'Morgan Wallen',
    'Luke Combs',
  ],

  // -------------------------------------------------------------- thématiques
  disney: [
    // Ici on nomme les chansons, pas les interprètes : le catalogue range les
    // bandes originales sous des noms d'artistes que personne ne connaît, et
    // une recherche « Disney » ramène les séries pour adolescents de Disney
    // Channel plutôt que les grands classiques.
    '#Libérée, délivrée|La Reine des Neiges',
    '#Hakuna Matata|Le Roi Lion',
    '#L\'amour brille sous les étoiles|Le Roi Lion',
    '#Je voudrais déjà être roi|Le Roi Lion',
    '#Sous l\'océan|La Petite Sirène',
    '#Partir là-bas|La Petite Sirène',
    '#Ce rêve bleu|Aladdin',
    '#Je suis ton meilleur ami|Aladdin',
    '#Histoire éternelle|La Belle et la Bête',
    '#C\'est la fête|La Belle et la Bête',
    '#Il en faut peu pour être heureux|Le Livre de la Jungle',
    '#Être un homme comme vous|Le Livre de la Jungle',
    '#Un jour mon prince viendra|Blanche-Neige',
    '#Heigh-Ho|Blanche-Neige',
    '#L\'air du vent|Pocahontas',
    '#Comme un homme|Mulan',
    '#Je suis ton ami|Toy Story',
    '#Les cloches de Notre-Dame|Le Bossu de Notre-Dame',
    '#De zéro en héros|Hercule',
    '#Le bleu lumière|Vaiana',
    '#Je veux y croire|Raiponce',
    '#Tout le monde veut devenir un cat|Les Aristochats',
    '#Souviens-toi de moi|Coco',
    '#Quand on prie la bonne étoile|Pinocchio',
    '#Un morceau de sucre|Mary Poppins',
    '#Supercalifragilisticexpialidocious|Mary Poppins',
    '#Tendre rêve|Cendrillon',
    '#Le monde est petit|Disney',
  ],
  'generiques de series': [
    'The Rembrandts|I\'ll Be There for You',
    'Ramin Djawadi|Main Title|Light of the Seven',
    'Kyle Dixon & Michael Stein|Stranger Things',
    'Barenaked Ladies|Big Bang Theory Theme',
    '#Goldorak|générique dessin animé',
    '#Albator|générique dessin animé',
    '#Candy|générique dessin animé',
    '#Les mystérieuses cités d\'or|générique',
    '#Ulysse 31|générique',
    '#Il était une fois la vie|générique',
    '#Inspecteur Gadget|générique',
    '#Nicky Larson|générique',
    '#Les chevaliers du zodiaque|générique',
    '#Chala Head Chala|Dragon Ball Z',
    '#Bioman|générique',
    '#Sailor Moon|générique',
    '#Je m\'appelle Hélène|Hélène Rollès',
    '#Sacré Charlemagne|générique',
    '#Mission Impossible Theme|Lalo Schifrin',
    '#Hawaii Five-O Theme|The Ventures',
    '#The X-Files|Mark Snow',
    '#Red Right Hand|Nick Cave',
    '#Westworld|Main Title Theme',
    '#Twin Peaks Theme|Angelo Badalamenti',
  ],
  'musiques de films': [
    'Hans Zimmer', 'John Williams', 'Ennio Morricone', 'Howard Shore',
    'Danny Elfman', 'Alexandre Desplat', 'Michel Legrand', 'Vladimir Cosma',
    'Ludovic Bource', 'Gabriel Yared', 'James Horner', 'Alan Silvestri',
    'Jerry Goldsmith', 'Thomas Newman', 'Clint Mansell', 'Ryuichi Sakamoto',
    'Nino Rota', 'Bernard Herrmann', 'Lalo Schifrin', 'Éric Serra',
    'Philippe Sarde', 'Georges Delerue', 'Maurice Jarre', 'Trent Reznor',
    'Ludwig Göransson', 'Rachel Portman',
  ],
  'musiques de jeux video': [
    'Koji Kondo', 'Nobuo Uematsu', 'Jeremy Soule', 'Mick Gordon',
    'Austin Wintory', 'Yasunori Mitsuda', 'Grant Kirkhope',
    'Martin O\'Donnell', 'Jesper Kyd', 'Christopher Tin', 'Olivier Derivière',
    'Inon Zur', 'Yoko Shimomura', 'Michiru Yamane', 'Motoi Sakuraba',
    'Yuzo Koshiro', 'Akira Yamaoka', 'Gareth Coker', 'Darren Korb',
    'Lena Raine', 'Toby Fox', 'Masayoshi Soken',
  ],
  'chansons de noel': [
    'Mariah Carey|All I Want for Christmas Is You',
    'Wham!|Last Christmas',
    'Bing Crosby|White Christmas',
    'Frank Sinatra|Let It Snow! Let It Snow! Let It Snow!|Jingle Bells',
    'Nat King Cole|The Christmas Song',
    'Michael Bublé|It\'s Beginning to Look a Lot Like Christmas|Santa Claus Is Coming to Town',
    'Brenda Lee|Rockin\' Around the Christmas Tree',
    'José Feliciano|Feliz Navidad',
    'Chris Rea|Driving Home for Christmas',
    'Band Aid|Do They Know It\'s Christmas?',
    'Shakin\' Stevens|Merry Christmas Everyone',
    'Tino Rossi|Petit Papa Noël',
    'Andy Williams|It\'s the Most Wonderful Time of the Year',
    'Dean Martin|Let It Snow',
    'Elvis Presley|Blue Christmas',
    'The Jackson 5|Santa Claus Is Comin\' to Town',
    'John Lennon|Happy Xmas (War Is Over)',
    'Boney M.|Mary\'s Boy Child',
    'Ariana Grande|Santa Tell Me',
    'Kelly Clarkson|Underneath the Tree',
    'Pentatonix|Hallelujah',
    'Céline Dion|So This Is Christmas',
    'Paul McCartney|Wonderful Christmastime',
  ],
  eurovision: [
    'ABBA|Waterloo',
    'Céline Dion|Ne partez pas sans moi',
    'Måneskin|ZITTI E BUONI',
    'Netta|Toy',
    'Salvador Sobral|Amar pelos dois',
    'Conchita Wurst|Rise Like a Phoenix',
    'Loreen|Euphoria|Tattoo',
    'Lordi|Hard Rock Hallelujah',
    'Alexander Rybak|Fairytale',
    'Marie Myriam|L\'oiseau et l\'enfant',
    'Barbara Pravi|Voilà',
    'Duncan Laurence|Arcade',
    'Kalush Orchestra|Stefania',
    'Sertab Erener|Everyway That I Can',
    'Ruslana|Wild Dances',
    'Helena Paparizou|My Number One',
    'Dima Bilan|Believe',
    'Lena|Satellite',
    'Emmelie de Forest|Only Teardrops',
    'Jamala|1944',
    'Amir|J\'ai cherché',
    'Bilal Hassani|Roi',
    'Katrina & The Waves|Love Shine a Light',
  ],
  'karaoke culte': [
    'Francis Cabrel|Je l\'aime à mourir|Petite Marie',
    'Michel Sardou|Les lacs du Connemara|Je vais t\'aimer|En chantant',
    'Claude François|Alexandrie Alexandra|Cette année-là',
    'Gloria Gaynor|I Will Survive',
    'Queen|Bohemian Rhapsody|Don\'t Stop Me Now',
    'Neil Diamond|Sweet Caroline',
    'Bonnie Tyler|Total Eclipse of the Heart|It\'s a Heartache',
    'Desireless|Voyage, voyage',
    'Los Lobos|La Bamba',
    'Village People|Y.M.C.A.',
    'Bon Jovi|Livin\' on a Prayer',
    'Journey|Don\'t Stop Believin\'',
    'Dalida|Mourir sur scène|Paroles, paroles',
    'K-Maro|Femme Like U',
    'Yannick|Ces soirées-là',
    'Garou|Belle',
    'Daniel Balavoine|L\'Aziza',
    'Charles Aznavour|Emmenez-moi|La bohème',
    'The Beatles|Hey Jude',
    'Oasis|Wonderwall',
    'The Cranberries|Zombie',
    'Toto|Africa',
    'Céline Dion|Pour que tu m\'aimes encore',
    'Joe Dassin|Les Champs-Élysées',
    'Patrick Sébastien|Les Sardines|Le petit bonhomme en mousse',
  ],
  'tubes de mariage': [
    'Patrick Sébastien|Les Sardines|Le petit bonhomme en mousse',
    'Village People|Y.M.C.A.',
    'Gloria Gaynor|I Will Survive',
    'Los del Río|Macarena',
    'Kool & The Gang|Celebration',
    'Earth, Wind & Fire|September',
    'Bee Gees|Stayin\' Alive',
    'ABBA|Dancing Queen|Mamma Mia',
    'Claude François|Alexandrie Alexandra',
    'Yannick|Ces soirées-là',
    'Michel Sardou|Les lacs du Connemara',
    'Guesch Patti|Étienne',
    'Ottawan|D.I.S.C.O.',
    'Boney M.|Rasputin|Daddy Cool',
    'The Trammps|Disco Inferno',
    'Sister Sledge|We Are Family',
    'Chic|Le Freak',
    'Ricky Martin|Livin\' la Vida Loca',
    'Lou Bega|Mambo No. 5',
    'Daft Punk|Get Lucky',
    'Bruno Mars|Uptown Funk',
    'Maître Gims|Sapés comme jamais',
    'Kendji Girac|Andalouse',
  ],
  'tubes de l\'ete': [
    'Luis Fonsi|Despacito',
    'OMI|Cheerleader',
    'Shakira|Waka Waka (This Time for Africa)|Hips Don\'t Lie',
    'Ricky Martin|Livin\' la Vida Loca|María',
    'Los del Río|Macarena',
    'Lou Bega|Mambo No. 5',
    'Kaoma|Lambada',
    'Las Ketchup|Aserejé (The Ketchup Song)',
    'Sean Paul|Temperature',
    'Magic System|Premier Gaou|Magic in the Air',
    'Kendji Girac|Andalouse|Color Gitano',
    'Stromae|Alors on danse',
    'Daddy Yankee|Gasolina',
    'J Balvin|Mi Gente',
    'Kungs|This Girl',
    'Bob Sinclar|Love Generation|World, Hold On',
    'Gipsy Kings|Bamboléo|Djobi Djoba',
    'Manu Chao|Bongo Bong|Me Gustas Tu',
    'Alizée|Moi... Lolita',
    'Collectif Métissé|Z Dance',
    'Carlos Vives|Robarte un Beso',
  ],
  'slows & love songs': [
    'Whitney Houston|I Will Always Love You',
    'Céline Dion|My Heart Will Go On|Pour que tu m\'aimes encore',
    'Bryan Adams|(Everything I Do) I Do It for You',
    'Aerosmith|I Don\'t Want to Miss a Thing',
    'Berlin|Take My Breath Away',
    'The Righteous Brothers|Unchained Melody',
    'Ed Sheeran|Perfect|Thinking Out Loud',
    'Adele|Someone Like You|Make You Feel My Love',
    'Elton John|Your Song|Can You Feel the Love Tonight',
    'Scorpions|Still Loving You|Wind of Change',
    'Roxette|It Must Have Been Love|Listen to Your Heart',
    'Extreme|More Than Words',
    'John Legend|All of Me',
    'Marvin Gaye|Let\'s Get It On',
    'Jean-Jacques Goldman|Puisque tu pars',
    'Francis Cabrel|Je l\'aime à mourir',
    'Étienne Daho|Duel au soleil',
    'Lara Fabian|Je t\'aime',
    'Garou|Sous le vent',
    'Calogero|Si seulement je pouvais lui manquer',
    'Sinéad O\'Connor|Nothing Compares 2 U',
    'Chris Isaak|Wicked Game',
  ],
  'comptines & enfants': [
    'Henri Dès', 'Aldebert', 'Chantal Goya', 'Pierre Lozère', 'Steve Waring',
    'Anne Sylvestre', 'Les Enfantastiques', 'Rémi', 'Gérard Dalton',
    'Les Petits Chanteurs à la Croix de Bois', 'Le Monde d\'Hugo',
    'Comptines et Chansons', 'Titounis', 'Pomme d\'Api', 'Bébé Lilly',
  ],
};

// Ambiances sans base d'artistes : on retombe sur les playlists Deezer, mais
// filtrées beaucoup plus sévèrement (voir index.js).
export const SANS_BASE = new Set(['hits du moment']);

// Mots dont la présence dans le titre d'une playlist prouve qu'elle parle bien
// du thème demandé. Sert au chemin de secours.
export const SYNONYMES = {
  disney: ['disney', 'pixar'],
  'generiques de series': ['serie', 'series', 'generique', 'generiques', 'tv'],
};

export function cleAmbiance(nom) {
  return String(nom)
    .normalize('NFD').replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .replace(/[()…]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

// Retrouve l'ambiance correspondant au libellé affiché dans l'application.
// « Chanson française (Brel, Piaf…) » → 'chanson francaise brel piaf'.
export function trouverAmbiance(libelle) {
  const c = cleAmbiance(libelle).replace(/,/g, '');
  if (AMBIANCES[c]) return AMBIANCES[c];
  for (const [cle, liste] of Object.entries(AMBIANCES)) {
    if (c.startsWith(cle) || cle.startsWith(c)) return liste;
  }
  return null;
}

export function estSansBase(libelle) {
  const c = cleAmbiance(libelle).replace(/,/g, '');
  for (const cle of SANS_BASE) if (c.startsWith(cle) || cle.startsWith(c)) return true;
  return false;
}
